/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hh_go2019_MainActivity */

#ifndef _Included_com_hh_go2019_MainActivity
#define _Included_com_hh_go2019_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hh_go2019_MainActivity
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hh_go2019_MainActivity_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_hh_go2019_MainActivity
 * Method:    testAndroid
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hh_go2019_MainActivity_testAndroid
  (JNIEnv *, jobject);

/*
 * Class:     com_hh_go2019_MainActivity
 * Method:    stringArrayFromJNI
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_hh_go2019_MainActivity_stringArrayFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
